const fse = require('fs-extra');
const path = require('path');

const MOCK_DIR = path.join(__dirname, '..', 'mock-evidence');

const structure = [
  {
    folder: 'imagenes',
    files: [
      'foto-001.jpg',
      'foto-002.jpg',
      'foto-003.jpg',
      'captura-001.png',
      'captura-002.png'
    ]
  },
  {
    folder: 'documentos',
    files: [
      'informe-2024.pdf',
      'contrato-A.pdf',
      'declaracion.pdf',
      'acta-reunion.docx',
      'notas-campo.docx'
    ]
  },
  {
    folder: 'datos',
    files: [
      'registros-enero.csv',
      'registros-febrero.csv',
      'configuracion.json'
    ]
  },
  {
    folder: 'videos',
    files: [
      'grabacion-001.mp4'
    ]
  },
  {
    folder: 'carpeta-vacia',
    files: []
  }
];

const rootFiles = ['reporte.txt'];

async function createMockData() {
  console.log(`Creating mock data in: ${MOCK_DIR}`);

  // Remove existing mock-evidence dir if present
  await fse.remove(MOCK_DIR);
  await fse.ensureDir(MOCK_DIR);

  // Create root-level files
  for (const fileName of rootFiles) {
    const filePath = path.join(MOCK_DIR, fileName);
    await fse.outputFile(filePath, `[MOCK] File: ${fileName}\nGenerated by createMockData.js\n`);
    console.log(`  Created: ${fileName}`);
  }

  // Create subfolders and their files
  for (const { folder, files } of structure) {
    const folderPath = path.join(MOCK_DIR, folder);
    await fse.ensureDir(folderPath);

    if (files.length === 0) {
      console.log(`  Created: ${folder}/ (empty)`);
    }

    for (const fileName of files) {
      const filePath = path.join(folderPath, fileName);
      await fse.outputFile(filePath, `[MOCK] File: ${fileName}\nFolder: ${folder}\nGenerated by createMockData.js\n`);
      console.log(`  Created: ${folder}/${fileName}`);
    }
  }

  // Summary
  console.log('\n--- Summary ---');
  let total = rootFiles.length;
  console.log(`  / (root): ${rootFiles.length} file(s) — ${rootFiles.join(', ')}`);
  for (const { folder, files } of structure) {
    console.log(`  ${folder}/: ${files.length} file(s)${files.length > 0 ? ' — ' + files.join(', ') : ''}`);
    total += files.length;
  }
  console.log(`  Total files: ${total}`);
  console.log('Done.');
}

createMockData().catch((err) => {
  console.error('Error creating mock data:', err.message);
  process.exit(1);
});
